services:
  redis_server:
    image: redis:alpine
    container_name: redis_server
    networks:
    - rag-app
    ports:
    - "6379:6379"
    volumes:
    - redis_data:/data
    - ./redis.conf:/etc/redis/redis.conf:ro
    command: redis-server /etc/redis/redis.conf

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: rabwah-backend
    image: rabwah-backend
    ports:
    - "8080:8080"
    - "8000:8000"
    networks:
    - rag-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
    - redis_server
  
  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    container_name: rabwah-frontend
    image: rabwah-frontend
    ports:
    - "80:5000"
    networks:
    - rag-app
    depends_on:
    - backend
    - redis_server

volumes:
  redis_data:
    driver: local

networks:  
  rag-app:
    driver: bridge