services:
  redis_server:
    image: redis:alpine
    container_name: redis_server
    networks:
    - rag-app
    ports:
    - "6379:6379"
    volumes:
    - redis_data:/data
    command: redis-server /etc/redis/redis.conf

  backend:
    image: marwanmohammed2500/rabwah-rag-system:rabwah-backend-latest
    container_name: rabwah-backend
    image: rabwah-backend
    ports:
    - "8080:8080"
    - "8000:8000"
    networks:
    - rag-app
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    image: marwanmohammed2500/rabwah-rag-system:rabwah-frontend-latest
    container_name: rabwah-frontend
    image: rabwah-frontend
    ports:
    - "80:5000"
    networks:
    - rag-app
    depends_on:
    - backend
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

volumes:
  redis_data:
    driver: local

networks:
  rag-app:
    driver: bridge