services:
  fastapi:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
    - "8080:8080"
    networks:
    - rag-app
  
  node:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    container_name: node-frontend
    ports:
    - "80:5000"
    networks:
    - rag-app
    depends_on:
    - fastapi
  
  admin:
    build: ..
    ports:
      - "8000:8000"
    depends_on:
      - fastapi
    container_name: admin-panel
    command: streamlit run src/admin_ui.py --server.port=8000 --server.baseUrlPath=/admin

networks:  
  rag-app:
    driver: bridge